D: 64
accelerator: null
accumulate_grad_batches: 1
adf_length: 13
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_first: true
benchmark: false
bidirection: true
cache_dataset: false
cache_dataset_filepath: ''
cached_dataset_filepath: ''
check_val_every_n_epoch: 1
checkpoint_callback: true
chromosome_length: 64
default_root_dir: null
deterministic: false
devices: null
distributed_backend: null
dropout: 0.1
epsilon: 1.0e-08
eval_batch_size: 128
eval_splits: []
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 0
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
h_adf: 4
h_main: 6
hidden_size: 128
ipus: null
k_folds: 10
l_adf: 9
l_main: 13
learning_rate: 2.0e-05
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
main_length: 19
max_arity: 3
max_epochs: 1
max_seq_length: 128
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_name_or_path: distilbert-base-uncased
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
mutation_rate: 0.203125
num_adf: 2
num_iter: 100
num_labels: 6
num_layers: 1
num_main: 2
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_terminal: 3
num_val_dataloader: 1
num_workers: 4
overfit_batches: 0.0
pin_memory: true
plugins: null
pop_size: 10
popsize: 10
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_dict_path: null
seed: 42
stochastic_weight_avg: false
sync_batchnorm: false
task_name: trec
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
train_batch_size: 128
truncated_bptt_steps: null
unfreeze_embed: true
use_simple_cls: false
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
